version: "3"

services:
  django:
    restart: always
    ports:
      - 8060:8080
    volumes:
      - '/var/www/gists42.com-frontend/static:/code/static'
      - '/var/www/gists42.com-frontend/templates:/code/templates'
